ja:
  errors:
    messages:
      taken: "は既に存在しています"